name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: 📁 Checkout Repo
        uses: actions/checkout@v2

      - name: 🛠 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 🛒 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install colorama
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 🏗 Build README
        run: python update.py

      - name: ⛳ Commit Update
        run: |-
          git add .
          git diff
          git config --global user.email "belivipro9x99@gmail.com"
          git config --global user.name "Belikhun Bot"
          git commit -m "🔮 README.md: Update README"
          git push